CREATE TABLE system_access_attempts (
  attempt_id     NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  username       VARCHAR2(128)          NOT NULL,
  attempt_time   TIMESTAMP              DEFAULT SYSTIMESTAMP NOT NULL,
  action         VARCHAR2(30),
  client_host    VARCHAR2(200),
  user_agent     VARCHAR2(4000),
  success_flag   CHAR(1) DEFAULT 'N',
  details        VARCHAR2(4000)
);

CREATE TABLE access_violation_log (
  violation_id   NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  username       VARCHAR2(128)          NOT NULL,
  violation_time TIMESTAMP              DEFAULT SYSTIMESTAMP NOT NULL,
  violation_type VARCHAR2(30)           NOT NULL,
  target_table   VARCHAR2(128),
  action_attempt VARCHAR2(30),
  client_info    VARCHAR2(4000),
  reason         VARCHAR2(4000)
);
