-- 1. LOGIN_AUDIT table
CREATE TABLE login_audit (
    audit_id      NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username      VARCHAR2(128) NOT NULL,           
    attempt_time  TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    login_status  VARCHAR2(10) 
                  CONSTRAINT chk_status CHECK (login_status IN ('SUCCESS','FAILED')) 
                  NOT NULL,
    ip_address    VARCHAR2(45)                      
);



 -- 2. SECURITY_ALERTS table 
CREATE TABLE security_alerts (
    alert_id       NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username       VARCHAR2(30) NOT NULL,
    failed_count   NUMBER NOT NULL,
    alert_time     TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    alert_message  VARCHAR2(500),
    email_to_notify VARCHAR2(60)                     
);




-- trigger beginning

CREATE OR REPLACE TRIGGER trg_failed_login_alert
  AFTER INSERT ON login_audit
  FOR EACH ROW
  WHEN (NEW.login_status = 'FAILED')
DECLARE
  PRAGMA AUTONOMOUS_TRANSACTION;   --because of the table muttating when using count

  v_failed_count  NUMBER;
  v_today         DATE := TRUNC(SYSDATE);
BEGIN
  -- Count failed attempts today 
  SELECT COUNT(*)
    INTO v_failed_count
    FROM login_audit
   WHERE username = :NEW.username
     AND login_status = 'FAILED'
     AND TRUNC(attempt_time) = v_today;

  IF v_failed_count > 2 THEN
    INSERT INTO security_alerts (username, failed_count, alert_message)
    VALUES (
      :NEW.username,
      v_failed_count,
      'SECURITY ALERT: ' || v_failed_count || 
      ' failed login attempts on ' || TO_CHAR(v_today, 'DD-MON-YYYY')
    );

    COMMIT;   
  END IF;
END;
/


--- testing trigger

-- let simulate 3 failed logins for user "Paul"
INSERT INTO login_audit (username, login_status, ip_address)
VALUES ('Paul', 'FAILED', '192.168.1.100');

INSERT INTO login_audit (username, login_status, ip_address)
VALUES ('Paul', 'FAILED', '192.168.1.100');

-- Third one to triggers the alert!
INSERT INTO login_audit (username, login_status, ip_address)
VALUES ('Paul', 'FAILED', '192.168.1.100');

select * from SECURITY_ALERTS;

